name: HawkEye
version: ${project.version}
main: org.cubeville.hawkeye.bukkit.HawkEyePlugin
author: Cubeville
authors: [GoalieGuy6]
softdepend: [WorldEdit]
description: Data logging plugin

commands:
    hawkeye:
        aliases: [hawk, ha, he, hk]